name: Infrastructure Destroy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to destroy'
        required: true
        type: choice
        options:
          - dev
          - staging
          - prod

permissions:
  id-token: write
  contents: read

jobs:
  destroy:
    permissions:
      id-token: write
      contents: read
    uses: stuartshay/shared-azure-health/.github/workflows/destroy-infrastructure.yml@master
    with:
      project-name: py-azure-health
      environment: ${{ inputs.environment }}
      resource-group: ${{ secrets.AZURE_RESOURCE_GROUP }}
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
